[workspace]
members = [
    "kvsserver",
    "kvsinterface",
    "kvscoordinator",
]
resolver = "2"

[workspace.dependencies]
# Local crates
kvsinterface = { version = "0.1.0", path = "kvsinterface" }

# Async runtime
tokio = { version = "1.47", features = ["rt-multi-thread", "macros", "full"] }
futures = "0.3.31"

# Serialization
serde = { version = "1.0.228", features = ["derive"] }

# RPC framework
tarpc = { version = "0.37.0", features = ["full", "tokio1"] }

# gRPC
tonic = "0.14"
prost = "0.14"
prost-types = "0.14"
tonic-prost = "0.14"
tonic-prost-build = "0.14"

# Error handling
anyhow = "1.0.100"
thiserror = "2.0.17"

# CLI
clap = { version = "4.5", features = ["derive"] }

# Utilities
dashmap = "6.1.0"
lazy_static = "1.5.0"
regex = "1.12.2"