[package]
name = "kvscoordinator"
version = "0.1.0"
edition = "2024"

[dependencies]
kvsinterface = { workspace = true }
clap = { workspace = true }
tarpc = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
futures = { workspace = true }
lazy_static = { workspace = true }
regex = { workspace = true }
thiserror = { workspace = true }